import { createSlice } from "@reduxjs/toolkit";
import { reset } from "../actions/actions";

// creating movieSlice with mini reducers and adding extraReducer to watch for the reser action type
const moviesSlice = createSlice({
  name: "movie",
  initialState: [],
  reducers: {
    addMovie(state, action) {
      state.push(action.payload);
    },
    removeMovie(state, action) {
      let movieToRemove = state.indexOf(action.payload);
      state.splice(movieToRemove, 1);
    },
  },
  extraReducers(builder) {
    builder.addCase(reset, (state, action) => {
      return [];
    });
  },
});

// exporting the action creators generated automatically by movieSlice
export const { addMovie, removeMovie } = moviesSlice.actions;

// exporting the the combined reducer generated by movieSlice
export const moviesReducer = moviesSlice.reducer;